config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get  "/" => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :show, :edit, :index, :create, :update]
    resources :orders, only: [:show, :update]
  end

  scope module: :public do
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :destroy, :update]
    get "/customers/quit" => "customers#quit"
    patch "/customers/out" => "customers#out"
    resources :customers, only: [:show, :update, :edit]
    resources :items, only: [:index, :show]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanx" => "orders#thanx"
    resources :orders, only: [:new, :index, :show, :create]
    root to: "homes#top"
    get "/about" => 'homes#about', as: 'about'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details

  has_one_attached :image

  def with_tax_price
    (price * 1.1).floor
  end


  validates :image, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0}


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.page(params[:page])
    @items_all = Item.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    end
  end

  def update
     @item = Item.find(params[:id])
     if @item.update(item_params)
       redirect_to admin_item_path(@item)
     else
       render :edit
     end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品編集</h2>
    </div>
  </div>
   <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto">
      <%= form_with model: @item, url: admin_item_path, local: true do |f| %>
      <table>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品画像 %></th>
          <td><%= f.file_field :image %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品名 %></th>
          <td><%= f.text_field :name, placeholder:"商品名" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :商品説明 %></th>
          <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
        </div>
      </tr>
      <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
      </tr>
        <div class="form-action">
          <td><%= f.submit "変更を保存", class:"btn btn-success" %></td>
        </div>
      </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>商品一覧</h2>
    </div>
    <div class="col-sm-2 px-sm-0 text-center mb-2">
      <%= link_to "商品新規登録", new_admin_item_path %>
    </div>
  </div>
    <div class="row my-3">
      <div class="col-sm-10 px-sm-0 offset-sm-1">
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
            </tr>
          </thead>
          <tbody>
          <% @items.each do |item| %>
            <tr>
              <td class="align-middle"><%= item.id %></td>
              <td class="align-middle"><%= link_to admin_item_path(item.id) do %>
                <u><%= item.name %></u>
              </td>
              <% end %>
              <td class="align-middle"><%= item.price %></td>
            </tr>
          </tbody>
          <% end %>
      </table>
      </div>
    </div>
  </div>
  <%= paginate @items, class:"text-center" %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>商品新規登録</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-10 px-sm-0 mx-auto mb-5">
      <%= form_with model: @item, url: admin_items_path, local: true do |f| %>
      <table>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品画像 %></th>
            <th><%= f.file_field :image, accept: "image/*" %></th>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, placeholder:"商品名" %></td>
          </div>
        </tr>
        <tr>
          <div class="form-group">
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, size: "50x5", placeholder:"ここに説明文を記述します" %></td>
          </div>
        </tr>
        <tr>
        <div class="form-group">
          <th><%= f.label :税抜価格 %></th>
          <td><%= f.text_field :price, placeholder:"1000" %>円</td>
        </div>
        </tr>
        <tr>
        <div class="form-action">
          <th><%= f.submit "新規登録", class:"btn btn-success" %></th>
        </div>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5 mb-5">
	<div class="row text-center text-xs-center text-sm-left text-md-left ">
    <div class="col-xs-12 col-sm-6 col-md-6 mx-auto text-right">
     <%= image_tag @item.image, width: "60%", format: "jpeg", fallback: "no_image.jpeg", class:"lb" %>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 item-details mx-auto">
      <h2><strong><%= @item.name %></strong></h2>
      <h4><%= simple_format(@item.introduction)%></h4>
      <h3>¥ <%= @item.with_tax_price %>(<%= (@item.price) %>) (税抜)</h3>
      <%= link_to "編集する", edit_admin_item_path, class:"btn btn-success" %>
      </div>
  </div>
</div>