config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get  "/" => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :show, :edit, :index, :create, :update]
    resources :orders, only: [:show, :update]
  end

  scope module: :public do
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :destroy, :update]
    get "/customers/quit" => "customers#quit"
    patch "/customers/out" => "customers#out"
    resources :customers, only: [:show, :update, :edit]
    resources :items, only: [:index, :show]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanx" => "orders#thanx"
    resources :orders, only: [:new, :index, :show, :create]
    root to: "homes#top"
    get "/about" => 'homes#about', as: 'about'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :email, uniqueness: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
    @customers_all = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    flash[:notice] = "会員情報を変更しました。"
    redirect_to admin_customer_path
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :telephone_number, :postal_code, :address, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>
  </div>
  <%= form_with model: @customer, url: admin_customer_path(@customer.id), local: :true, method: :put do |f| %>
    <div class="row">
      <div class="col-2 offset-md-1"><%= f.label "名前" %></div>
      <div class="col-1 text-right pr-0"><%= f.label "(姓)" %></div>
      <div class="col-2"><%= f.text_field :last_name, :size => "10", placeholder: "長野" %></div>
      <div class="col-1 text-right pr-0"><%= f.label "(名)" %></div>
      <div class="col-3"><%= f.text_field :first_name, :size => "10", placeholder: "花子" %></div>
    </div>
    <div class="row">
      <div class="col-2 offset-md-1"><%= f.label "フリガナ" %></div>
      <div class="col-1 text-right pr-0"><%= f.label "(セイ)" %></div>
      <div class="col-2"><%= f.text_field :last_name_kana, :size => "10", placeholder: "ナガノ" %></div>
      <div class="col-1 text-right pr-0"><%= f.label "(メイ)" %></div>
      <div class="col-3"><%= f.text_field :first_name_kana, :size => "10", placeholder: "ハナコ" %></div>
    </div>
    <div class="row">
      <div class="col-3 offset-md-1"><%= f.label "メールアドレス" %></div>
      <div class="col-3"><%= f.email_field :email, :size => "25", placeholder: "sample@example.com" %></div>
    </div>
    <div class="row">
      <div class="col-3 offset-md-1"><%= f.label "郵便番号(ハイフンなし)" %></div>
      <div class="col-3"><%= f.text_field :postal_code, :size => "10", placeholder: "1001000" %></div>
    </div>
    <div class="row">
      <div class="col-3 offset-md-1"><%= f.label "住所" %></div>
      <div class="col-3"><%= f.text_field :address, :size => "40", placeholder: "東京都渋谷区代々木神園町0-0" %></div>
    </div>
    <div class="row">
      <div class="col-3 offset-md-1"><%= f.label "電話番号(ハイフンなし)" %></div>
      <div class="col-3"><%= f.text_field :telephone_number, placeholder: "08012345678" %></div>
    </div>
    <div class="row">
      <div class="col-3 offset-md-1"><%= f.label "会員ステータス" %></div>
      <div class="col-3"><%= f.radio_button :is_deleted, :false %>
        <%= f.label :is_deleted, "有効" %>
        <%= f.radio_button :is_deleted, :true %>
        <%= f.label :is_deleted, "退会" %>
      </div>
    </div>

    <div class="row mb-2">
      <div class="col-lg-6 px-sm-0 offset-sm-1">
        <%= f.submit "変更を保存", class:"btn btn-success my-4" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2>会員一覧</h2>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-sm-10 px-sm-0 offset-sm-1">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-active">会員ID</th>
            <th class="table-active">氏名</th>
            <th class="table-active">メールアドレス</th>
            <th class="table-active">ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td class="align-middle"><%= customer.id %></td>
              <td class="align-middle"><u><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class:"font-weight-bold" %></u></td>
              <td class="align-middle"><%= customer.email %></td>
              <td class="align-middle">
                <% if customer.is_deleted == false %>
                  <p class="text-success font-weight-bold">有効</p>
                <% else %>
                  <p class="text-secondary">退会</p>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= paginate @customers, class:"text-center" %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-sm-8 px-sm-0 offset-sm-1">
      <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 px-sm-0 offset-sm-1">
      <table class="table table-bordered">
        <tr>
          <th class="table-active">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="table-active">氏名</th>
          <td><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <th class="table-active">フリガナ</th>
          <td><%= @customer.last_name_kana + @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th class="table-active">郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th class="table-active">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th class="table-active">電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th class="table-active">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th class="table-active">会員ステータス</th>
          <% if @customer.is_deleted == false %>
          <td class="text-success font-weight-bold">有効</td>
          <% else %>
          <td class="text-secondary">退会</td>
          <% end %>
        </tr>

      </table>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-lg-6 px-sm-0 offset-sm-1">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success my-1 mx-4 px-4" %>
      <%= link_to "注文履歴一覧を見る", admin_path(id: @customer), class:"btn btn-primary mx-4 px-4" %>
    </div>
  </div>

</div>