config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  namespace :admin do
    get  "/" => "homes#top"
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:new, :show, :edit, :index, :create, :update]
    resources :orders, only: [:show, :update]
  end

  scope module: :public do
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :destroy, :update]
    get "/customers/quit" => "customers#quit"
    patch "/customers/out" => "customers#out"
    resources :customers, only: [:show, :update, :edit]
    resources :items, only: [:index, :show]
    post "/orders/confirm" => "orders#confirm"
    get "/orders/thanx" => "orders#thanx"
    resources :orders, only: [:new, :index, :show, :create]
    root to: "homes#top"
    get "/about" => 'homes#about', as: 'about'
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer
  has_many :items, through: :order_details

  validates :total_amount, presence: true
  validates :payment_method, presence: true
  validates :pastage, presence: true
  validates :address, length: { in: 1..48 }
  validates :postal_code, presence: true
  validates :name, length: { in: 1..32 }



  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @orders = Order.all
    @order_details = Item.where(order_id: @order)
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order)
    if @order.update(order_status_params)
      if @order.order_status.include?("入金確認")
         @order_details.update( production_status: 1)
      end
    flash[:success] = "制作ステータスを変更しました。"
    redirect_to admin_order_path(@order)
    else
      render "show"
    end
  end

  private

  private
   def order_params
      params.require(:order).permit(:customer_id, :postal_code, :address, :payment_method, :pastage, :total_amount)
   end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="col-sm-10"><h2>注文履歴詳細</h2></div>
  <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
    <table class="table table-bordered">
        <tr>
          <th class="table-active" style="width:20%">購入者</th>
          <td class="link"><%= link_to admin_customer_path do %><%= @order.customer.last_name + @order.customer.first_name %><% end %></td>
        </tr>
        <tr><th class="table-active" style="width:20%">注文日</th><td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td></tr>
        <tr><th class="table-active" style="width:20%">配送先</th><td>〒<%= @order.postal_code %> <%= @order.address %> <%= @order.name %></td></tr>
        <tr><th class="table-active" style="width:20%">支払い方法</th><td><%= @order.payment_method_i18n %></td></tr>
    </table>
  <% end %>
  <div class="row">
    <div class="col-sm-8">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-active">商品名</th>
            <th class="table-active">単価(税込)</th>
            <th class="table-active">数量</th>
            <th class="table-active">小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
          <tr>
            <td class="align-middle"><%= order_detail.item.name %> </td>
            <td class="align-middle"><%= order_detail.tax_price %></td>
            <td class="align-middle"><%= order_detail.amount %></td>
            <td class="align-middle"><%= order_detail.amount * order_detail.tax_price %>円</td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-4">
      <table class="table table-bordered">
        <tr>
          <th class="table-active" style="width:50%">商品合計</th>
          <td>
            <%= @order.total_amount %>円
          </td>
        </tr>
        <tr><th class="table-active" style="width:50%">送料</th><td><%= @order.pastage %>円</td></tr>
        <tr>
          <th class="table-active" style="width:50%">請求金額合計</th>
          <td>
            <%= @order.total_amount %> 円
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>